### ISSUE TITLE
wuff with eclipse-neon -  SWT parts not available at compile time

### ISSUE THREAD

**Issue by de-jcup** [akhikhl/wuff#114]
Hello, I am a little bit stuck on a problem - maybe you can help:
### Info

I am developing a eclipse integration for eclipse called egradle (https://github.com/de-jcup/egradle) and I want to execute my testcases in complete eclipse environment so I can test eclipse parts too (currently I don't so many parts are not tested). To eat my own dog food I decided to do the test execution also with gradle so I started to use wuff...
### Changes made to get wuff on eclipse-neon running

My target platform is eclipse-neon, I setup the wuff-depencies in 
https://github.com/de-jcup/egradle/blob/feature-84-make-eclipse-projects-built-by-gradle/build.gradle
to work with eclipse-neon (3.6.1)
### Download + Installation fine

The downloads and the installation to ./wuff are working, all fine. 
### Build failes on compileJava

at 
https://travis-ci.org/de-jcup/egradle/builds/167167495
(or as raw log in https://api.travis-ci.org/jobs/167167496/log.txt?deansi=true)

you can see I am full missing all kind of org.eclipse.swt imports:
e.g.
`/home/travis/build/de-jcup/egradle/egradle-plugin-main/src/main/java-eclipse/de/jcup/egradle/eclipse/Activator.java:24: error: package org.eclipse.swt.custom does not exist`

but when I execute
./gradlew :egradle-plugin-main:dependencies

at the ouptut, I see the org.eclipse.swt plugin apearing
### Question

All I want to do is currently a simple compile and execute all test cases.
So what goes wrong?

**Comment by davidmichaelkarr** [comment]
I suggest you examine the history of recent responses to issues in this project.

Is there some reason Buildship isn't sufficient for you?

**Comment by de-jcup** [comment]
### recent responses to issues:

I found nothing about eclipse-neon, so I started to configure for 3.6
Also I found nothing about missing SWT as well - so I started this issue.

### buildship:

Hmm.. I tried it (and Gradle IDE) and it felt not good 
What I want is simply
- execute gradle, 
- easy synch mechansim (e.g. import all existing gradle build results to eclipse junit view - egradle does 4500 test imports in less than 2 seconds at my work...)
- execute junit tests inside ui on a fast way (e.g. simply click on test method and execute as junit test...)
- use eclipse and console parallel without any conflicts
- have access to root project parts without duplicated parts etc.
- lightweight integration. no special imports necessary, a simple "cleanEclipse eclipse"+ "import existing projects" is all. Means: always working...
- no conflicts on importing projects in my eclipse workplace at work
  and it was not fulfilled sorry. So I decided to write my own integration and I am happy with it any my collegues too...
  (see also https://github.com/de-jcup/egradle/wiki/FAQ)
